name: Get number of quic enabled websites

on:
  workflow_dispatch: # enable manual run
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false
  schedule:
    - cron: '0 7 * * *'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17


      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Download 1M Sites Data
        run: |
          sudo apt-get install wget unzip -y
          wget -P ./data https://statvoo.com/dl/top-1million-sites.csv.zip
          mv ./data/top-1million-sites.csv.zip ./data/top-1million-sites-${{  steps.date.outputs.date }}.csv.zip
          unzip ./data/top-1million-sites-${{  steps.date.outputs.date }}.csv.zip -d ./data/

      - name: Build
        run: go run main.go

      - name: Number of no QUIC conn. established
        id: noquic
        run: echo "::set-output name=noquic::$(wc -l < headers/${{ steps.date.outputs.date }}/no-quic-implementation-${{ steps.date.outputs.date }}.txt)"

      - name: Create data
        run: |
         echo "${{ steps.date.outputs.date }},${{ steps.noquic.outputs.noquic }}" >> data/no-quic-conn.csv

      - name: Cleanup csv data
        run: rm -rf ./data/top-1m.csv

      - name: Commit SS push
        run: |
          git config --global user.email "robotcuk@randommail.com"
          git config --global user.name "robotcuk"
          git add 'data/*'
          git add 'headers/*'
          git commit -m "${{ steps.noquic.outputs.noquic }} : no quic conn. established"
          git push origin -f main
        env:
         GITHUB_TOKEN: ${{ secrets.ROBOTCUK }}
